# -*- conding:utf-8 -*-

{
    'name': 'Modulo de Paz y Salvo',
    'version': '1.0',
    'depends': [
                'base',
                'contacts',
                'hr',
                'hr_contract',
                'account',
                'sale_management',
                'crm',
                'website',
                'stock',
                'purchase',
                'point_of_sale',
                'project',
                'website_sale',
                'mrp',
                'mass_mailing',
                'hr_expense',
                'hr_holidays',
                'hr_recruitment',
                'maintenance',
                'website_slides',
                'website_event',
                'calendar',
                'fleet',
                'website_blog',
                'im_livechat',
                'survey',
                'board',
                'repair',
                'hr_attendance',
                'mass_mailing_sms',
                'note',
                'website_forum',
                'hr_skills',
                'lunch',
                'website_hr_recruitment',
                'payment_odoo_by_adyen',
                'payment_adyen',
                'payment_alipay',
                'payment_authorize',
                'payment_buckaroo',
                'payment_ingenico',
                'payment_paypal',
                'payment_payulatam',
                'payment_payumoney',
                'payment_stripe',
                'payment_sips',
                'web'
],
    'author': 'Freddy Alexander Urrego Beltran',
    'website': 'https://www.udemy.com/',
    'category': 'Paz y Salvo',
    'summary': 'Modulo de Paz y Salvo',
    'description': """
        Modulo para hacer formularios de Paz y Salvo de los empleados
    """,
    'data': ['views/view_pazysalvo.xml',
             'views/menu.xml',
             'security/security_groups.xml',
             'security/ir.model.access.csv',
             'security/pazysalvo_rules.xml'],
}