# -*- conding:utf-8 -*-

from odoo import fields, models, api

class HrContract(models.Model):
    _inherit = 'hr.contract'

    active = fields.Boolean(string='Activo', store=True, copied=True, tracking=0, )
    activity_date_deadline = fields.Date(string='Siguiente plazo de actividad', readonly=True, tracking=0, )
    activity_exception_icon = fields.Char(string='Icono', readonly=True, tracking=0, )
    activity_summary = fields.Char(string='Resumen de la siguiente actividad', tracking=0, )
    activity_type_icon = fields.Char(string='Ícono de tipo de actvidad', readonly=True, tracking=0, )
    apply_procedure_2 = fields.Boolean(string='Aplicar Procedimiento 2', store=True, copied=True, tracking=0, )
    apprentice_to_worker_date = fields.Date(string='Fecha de Cambio a Etapa Productiva', store=True, copied=True,
                                            tracking=0, )
    auxiliar = fields.Boolean(string='Auxiliar', store=True, copied=True, tracking=0, )
    calendar_mismatch = fields.Boolean(string='No coinciden los calendarios', readonly=True, tracking=0, )
    change_date = fields.Date(string='Fecha Efectiva de Vacaciones', store=True, copied=True, tracking=0, )
    compensation_flexible = fields.Boolean(string='Compensacion Flexible', store=True, copied=True, tracking=0, )
    concat_contract = fields.Char(string='Personal', store=True, readonly=True, tracking=0, )
    contract_days = fields.Integer(string='Días de Contrato', store=True, copied=True, tracking=0, )
    date_end = fields.Date(string='Fecha final', store=True, copied=True, tracking=100, )
    date_print = fields.Date(string='Fecha de Impresión de Contrato', store=True, copied=True, tracking=0, )
    date_ref_holiday_book = fields.Date(string='Fecha referencia', store=True, copied=True, tracking=0, )
    date_start = fields.Date(string='Fecha de inicio', store=True, required=True, copied=True, tracking=100, )
    days_config = fields.Boolean(string='Días Configurados', readonly=True, tracking=0, )
    days_expire = fields.Integer(string='Dias a vencer', store=True, readonly=True, tracking=0, )
    days_left = fields.Float(string='Días restantes', store=True, readonly=True, copied=True, tracking=0, )
    days_left_holidays = fields.Float(string='Días Pendientes', store=True, copied=True, tracking=0, )
    deduction_dependents = fields.Boolean(string='Dependientes', store=True, copied=True, tracking=0, )
    due_date = fields.Date(string='Fecha de vencimiento', readonly=True, tracking=0, )
    duration = fields.Integer(string='Duration', store=True, copied=True, tracking=0, )
    fecha_novedad = fields.Date(string='Fecha de Novedad', store=True, copied=True, tracking=1, )
    first_contract_date = fields.Date(string='Primera fecha del contrato', readonly=True, tracking=0, )
    high_risk = fields.Boolean(string='Alto Riesgo', store=True, copied=True, tracking=0, )
    hours_comp_turno = fields.Integer(string='Horas compensadas por turno', store=True, copied=True, tracking=0, )
    jornada_ordinaria_dom = fields.Float(string='Jornada Domingos', store=True, copied=True, tracking=0, )
    jornada_ordinaria_fest = fields.Float(string='Jornada Festivos', store=True, copied=True, tracking=0, )
    limit_deductions = fields.Boolean(string='Limitar Deducciones al 50% de Devengos', store=True, copied=True,
                                      tracking=0, )
    message_attachment_count = fields.Integer(string='Nº de archivos adjuntos', readonly=True, tracking=0, )
    message_has_error = fields.Boolean(string='Error de Envío de Mensaje', readonly=True, tracking=0, )
    message_has_error_counter = fields.Integer(string='Numero de errores', readonly=True, tracking=0, )
    message_has_sms_error = fields.Boolean(string='Error de entrega del SMS', readonly=True, tracking=0, )
    message_is_follower = fields.Boolean(string='Es un seguidor', readonly=True, tracking=0, )
    message_needaction = fields.Boolean(string='Acción requerida', readonly=True, tracking=0, )
    message_needaction_counter = fields.Integer(string='Número de acciones', readonly=True, tracking=0, )
    message_unread = fields.Boolean(string='Mensajes sin leer', readonly=True, tracking=0, )
    message_unread_counter = fields.Integer(string='Nº de mensajes sin leer', readonly=True, tracking=0, )
    minimum_wage = fields.Boolean(string='Devenga Salario Mínimo', store=True, copied=True, tracking=0, )
    my_activity_date_deadline = fields.Date(string='My Activity Deadline', readonly=True, tracking=0, )
    name = fields.Char(string='Referencia contrato', store=True, required=True, copied=True, tracking=0, )
    new_check = fields.Boolean(string='Nuevo', readonly=True, tracking=0, )
    new_check_save = fields.Boolean(string='Nuevo.', store=True, readonly=True, tracking=0, )
    nota_retiro = fields.Char(string='Observaciones del Retiro', store=True, copied=True, tracking=1, )
    notes = fields.Text(string='Notas', store=True, copied=True, tracking=0, )
    percentage_equivalence = fields.Float(string='Porcentaje Equivalencia', store=True, copied=True, tracking=0, )
    permit_no = fields.Char(string='Número de permiso de trabajo', tracking=100, )
    remote_work_allowance = fields.Boolean(string='Aplica Auxilio de Conectividad', store=True, copied=True,
                                           tracking=0, )
    required_date_end = fields.Boolean(string='Obligatorio Fecha Finalización', readonly=True, tracking=0, )
    restrict_schedule = fields.Boolean(string='Restriccion en programación', readonly=True, tracking=0, )
    risk_percentage = fields.Float(string='Porcentaje de Riesgo', readonly=True, tracking=0, )
    settlement_date = fields.Date(string='Fecha de liquidación', store=True, copied=True, tracking=0, )
    skip_commute_allowance = fields.Boolean(string='Omitir Auxilio de Transporte', store=True, copied=True,
                                            tracking=0, )
    temp_fix = fields.Float(string='Ajuste temporal de sueldo', store=True, copied=True, tracking=0, )
    termino = fields.Char(string='Terminos', store=True, copied=True, tracking=0, )
    trial_date_end = fields.Date(string='Fin del periodo de prueba', store=True, copied=True, tracking=0, )
    trial_date_start = fields.Date(string='Periodo de Prueba', store=True, copied=True, tracking=0, )
    type_job_labor = fields.Char(string='Tipo de Obra o Valor', store=True, copied=True, tracking=0, )
    valor_mensual_horas = fields.Float(string='Valor mensual de horas', store=True, copied=True, tracking=0, )
    visa_expire = fields.Date(string='Fecha expiración visado', tracking=100, )
    visa_no = fields.Char(string='Número de Visado', tracking=100, )
    withholding_percent = fields.Float(string='Porcentaje de Retención', store=True, copied=True, tracking=0, )
    workcenter = fields.Char(string='Centro de Trabajo', store=True, copied=True, tracking=0, )
